### ISSUE TITLE
Weird structure of main.cpp

### ISSUE THREAD

**Issue by mchalupa** [petrv7/llvm2c#11]
1) Does creating the program need to be in any try-catch block? https://github.com/petrv7/llvm2c/blob/master/main.cpp#L38 .
The try-catch blocks take care of parsing arguments, IMHO the line 38 should be moved after these try-catch blocks.

2) Is the file always the first argument? parse_command_line does not give you the input files? If not, I suggest to use CommandLine from LLVM, it has even simpler API than the one that you use.

**Comment by petrv7** [comment]
Replaced Boost program options with LLVM CommandLine
