### ISSUE TITLE
[code review] Notes and questions

### ISSUE THREAD

**Issue by mchalupa** [petrv7/llvm2c#13]
- [x] Block::parseCallInstruction is terribly long, you should split it into several methods/functions
- [x] Block.cpp:835: AE variable is not used
- [x] Block.cpp:974: This case would deserve a comment
- [x] Block.cpp:981,993,1016: Is it alright that you can fall-through and continue executing the method after creating the expression? I guess that the conditions are mutually exclusive, but the code is worse readable and less efficient like this.
- [x] Func.cpp:185: Why is this printing needed, it should be handled in some of the `print()` methods, shouldn't? Types do not have print method?
- [x] Methods `toString`, `saveFile`, and `print` greatly duplicate code. You should have just one method that takes a generic stream and than `toString`, `saveFile`, and `print` can be just wrappers around this method that open the correct stream (stringstream or filestream) and call this method with the right stream (and can be actually defined just once in some parent class)
- [x] Somewhere you could get rid of superfluous parenthesis in printing, but I guess it's fine.

**Comment by petrv7** [comment]
InlineAsm parsing is moved to parseInlineASM function, added returns to createConstantValue function, removed unused variables

**Comment by mchalupa** [comment]
Note: `parseInlineASM` is still quite long, as well as `parseStoreInst`. Since there are no comments, it is hard to read them (if you structure the code into functions/methods that have nice names, then you see what the parts of the code do).
